# HDMI events don't trigger properly, so instead trigger off the specific keyboard being used.

[[Rules]]
PropName  = "ID_SERIAL"
PropValue = "413c_Dell_KB216_Wired_Keyboard"
Subsystem = "input"
Action = "add"
Command = "/bin/sh"
Args = ["-c", "sleep 1 && flock --nonblock $HOME/.cache/.toggle-external-display /bin/sh -c 'toggle-external-display only && sleep 5'"]

[[Rules]]
PropName  = "ID_SERIAL"
PropValue = "413c_Dell_KB216_Wired_Keyboard"
Subsystem = "input"
Action = "remove"
Command = "/bin/sh"
Args = ["-c", "sleep 1 && flock --nonblock $HOME/.cache/.toggle-external-display /bin/sh -c 'toggle-external-display off && sleep 5'"]

[[Rules]]
PropName  = "PRODUCT"
PropValue = "3/46d/c31c/110"
Subsystem = "input"
Action = "add"
Command = "/bin/sh"
Args = ["-c", "sleep 1 && flock --nonblock $HOME/.cache/.toggle-external-display /bin/sh -c 'toggle-external-display right-of && sleep 2' && i3-windows-to-secondary-output"]

[[Rules]]
PropName  = "PRODUCT"
PropValue = "3/46d/c31c/110"
Subsystem = "input"
Action = "remove"
Command = "/bin/sh"
Args = ["-c", "sleep 1 && flock --nonblock $HOME/.cache/.toggle-external-display /bin/sh -c 'toggle-external-display off && sleep 5'"]
