[colors]
ansi = [
      "#282c34", # black
      "#e06c75", # red
      "#98c379", # green
      "#d19a66", # yellow
      "#61afef", # blue
      "#c678dd", # magenta
      "#56b6c2", # cyan
      "#abb2bf", # white
]
brights = [
      "#5c6370", # black
      "#e06c75", # red
      "#98c379", # green
      "#d19a66", # yellow
      "#61afef", # blue
      "#c678dd", # magenta
      "#56b6c2", # cyan
      "#ffffff", # white
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'
background = '#000000'
selection_bg = '#ffffff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'OneDark'
