# Docs: https://docs.atuin.sh/configuration/config/

auto_sync = true
command_chaining = true
ctrl_n_shortcuts = false
enter_accept = false
exit_mode = "return-original"
filter_mode_shell_up_key_binding = "session"
history_filter = [
  # Don't track commands that start with a space
  "^ .+",
]
keymap_cursor = { emacs = "blink-block", vim_insert = "steady-bar", vim_normal = "steady-block" }
keymap_mode = "vim-insert"
local_timeout = 5
max_preview_height = 5
network_connect_timeout = 30
network_timeout = 30
search_mode = "fuzzy"
secrets_filter = true
show_help = true
show_tabs = true
style = "compact"
sync_address = "https://atuin.nlx.one"
sync_frequency = "0"  # 0 = immediate
workspaces = true

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "dotnet",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "nats",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

## Set commands that should be totally stripped and ignored from stats
common_prefix = ["sudo"]

[keys]
scroll_exits = false

[sync]
records = true

[daemon]
enabled = true
sync_frequency = 120

[search]
filters = [ "global", "host", "session", "workspace", "directory" ]
